### ISSUE TITLE
App is crashing on android apk -  java.lang.Error: UnexpectedData

### ISSUE THREAD

**Issue by bobangajicsm** [react-native-community/react-native-svg#1109]
App runs normally on metro server while developing. But after I build apk and install it on my phone it crashes with following error 

```
 Caused by: java.lang.Error: UnexpectedData
        at com.horcrux.svg.PathParser.parse(PathParser.java:49)
        at com.horcrux.svg.PathView.setD(PathView.java:31)
        at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java:395)
```

versions are "react-native-svg": "^9.9.4", and "react-native": "0.59.2".

**Comment by bobangajicsm** [comment]
Issue was related to d property and moveTo coordinates which needs to be first.

**Comment by CaptainJeff** [comment]
@bobangajicsm can you explain what you meant by 

`Issue was related to d property and moveTo coordinates which needs to be first.`
