### ISSUE TITLE
ArrayIndexOutOfBoundsException in 9.12.0

### ISSUE THREAD

**Issue by mars-lan** [react-native-community/react-native-svg#1162]
# Bug

Start seeing this exception in Android after upgrading from 9.11.1 to 9.12.0.

```
java.lang.ArrayIndexOutOfBoundsException
        at android.graphics.DashPathEffect.<init>(DashPathEffect.java:36)
        at com.horcrux.svg.RenderableView.setupStrokePaint(RenderableView.java:454)
        at com.horcrux.svg.RenderableView.draw(RenderableView.java:367)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:102)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:102)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:325)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:302)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:253)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:104)
```

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 258.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /var/folders/v8/3w7mrmvn5qj2p8xy7t7bcmfr0000gn/T/yarn--1571675743661-0.8771602729450789/node
    Yarn: 1.17.3 - /var/folders/v8/3w7mrmvn5qj2p8xy7t7bcmfr0000gn/T/yarn--1571675743661-0.8771602729450789/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 21, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom_64, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM EABI v7a, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.10.2 => 16.10.2 
    react-native: 0.60.5 => 0.60.5
```

Library version: 9.12.0

**Comment by mars-lan** [comment]
Actually never mind, the culprit turns out to be `react-native-circular-progress` 1.3.2
