### ISSUE TITLE
Crashing on android

### ISSUE THREAD

**Issue by silverspace** [react-native-community/react-native-svg#120]
I just got this crash on react-native-svn:4.1.3 with react-native:0.31.0. The crash happened on the initial render (looks to be caused by RNSVGViewBoxShadowNode.mAlign being null). 

I can work around this by adding align="none" to my javascript SVG Image attributes. 

08-18 17:39:49.948 4726-4726/com.samsara.driver E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.samsara.driver, PID: 4726
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                      at com.horcrux.svg.RNSVGViewBoxShadowNode.getTransform(RNSVGViewBoxShadowNode.java:140)
                                                                      at com.horcrux.svg.RNSVGImageShadowNode.doRender(RNSVGImageShadowNode.java:201)
                                                                      at com.horcrux.svg.RNSVGImageShadowNode.tryRender(RNSVGImageShadowNode.java:249)
                                                                      at com.horcrux.svg.RNSVGImageShadowNode.draw(RNSVGImageShadowNode.java:120)
                                                                      at com.horcrux.svg.RNSVGGroupShadowNode.draw(RNSVGGroupShadowNode.java:46)
                                                                      at com.horcrux.svg.RNSVGGroupShadowNode.draw(RNSVGGroupShadowNode.java:46)
                                                                      at com.horcrux.svg.RNSVGSvgViewShadowNode.drawChildren(RNSVGSvgViewShadowNode.java:84)
                                                                      at com.horcrux.svg.RNSVGImageShadowNode$1.onNewResultImpl(RNSVGImageShadowNode.java:140)
                                                                      at com.facebook.imagepipeline.datasource.BaseBitmapDataSubscriber.onNewResultImpl(BaseBitmapDataSubscriber.java:64)
                                                                      at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:48)
                                                                      at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:181)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6939)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
08-18 17:39:49.948 4726-4797/com.samsara.driver I/System.out: (HTTPLog)-Static: i

**Comment by magicismight** [comment]
Thanks for reporting this.
But I cannot reproduct this issue, can you provide more detail with the js code?

**Comment by silverspace** [comment]
I am not able to reproduce either, so I suspect this was an issue with my environment referencing stale npm packages. I've removed my align="none" attribute, and will re-open if this becomes an issue again.
