### ISSUE TITLE
Crash caused by java.lang.Error: InvalidNumber

### ISSUE THREAD

**Issue by JinYuSha0** [react-native-community/react-native-svg#1282]
# Bug

"react-native-svg": "^9.13.6"

It crash on some model phone, e.g: (Samsung A50).

```bash
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' of a view managed by: RNSVGPath
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.a(ViewManagersPropertyCache.java:122)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.a(ViewManagerPropertyUpdater.java:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.a(ViewManagerPropertyUpdater.java:24)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:52)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:23)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:46)
       at com.facebook.react.uimanager.UIViewOperationQueue.i(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:48)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.a(ViewManagersPropertyCache.java:23)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.a(ViewManagerPropertyUpdater.java:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.a(ViewManagerPropertyUpdater.java:24)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:52)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:23)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:46)
       at com.facebook.react.uimanager.UIViewOperationQueue.i(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:48)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

Caused by java.lang.Error: InvalidNumber
       at com.horcrux.svg.PathParser.e(PathParser.java:194)
       at com.horcrux.svg.PathParser.c(PathParser.java:6)
       at com.horcrux.svg.PathParser.a(PathParser.java:453)
       at com.horcrux.svg.PathView.setD(PathView.java)
       at com.horcrux.svg.RenderableViewManager$PathViewManager.setD(RenderableViewManager.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.a(ViewManagersPropertyCache.java:23)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.a(ViewManagerPropertyUpdater.java:10)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.a(ViewManagerPropertyUpdater.java:24)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:52)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:23)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:46)
       at com.facebook.react.uimanager.UIViewOperationQueue.i(UIViewOperationQueue.java:53)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:48)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```

**Comment by JinYuSha0** [comment]
Is there something wrong with my svg code?
but it only crash on some phones, the worst thing is i don't have these phones, can anyone help me?

```
export default class extends PureComponent<Props> {
    getRate = () => {
        const { max, min, value } = this.props
        let rate = Math.floor((value - min) * 100 / (max - min))
        if (rate < 0) return  0
        if (rate > 100) return 100
        return rate
    }

    render() {
        const {
            width,
            height,
            radius,
            angle,
            outArcColor,
            progressColor,
            strokeWidth,
            progressStrokeWidth,
            dotRadius,
            dotColor,
            children,
        } = this.props

        const cx = width / 2
        const cy = height / 2
        const prad = angle / 2 * (Math.PI / 180)
        const startX = -(Math.sin(prad) * radius) + cx
        const startY = cy + Math.cos(prad) * radius
        const endX = Math.sin(prad) * radius + cx
        const endY = cy + Math.cos(prad) * radius

        const progress = Math.floor(this.getRate() * (360 - angle) / 100)
        const t = progress + angle / 2
        const progressX = cx - Math.sin(t * (Math.PI / 180)) * radius
        const progressY = cy + Math.cos(t * (Math.PI / 180)) * radius

        const circleDescriptions = [
            'M',
            startX,
            startY,
            'A',
            radius,
            radius,
            0,
            1,
            1,
            endX,
            endY,
        ].join(' ')

        const progressDescription = [
            'M',
            startX,
            startY,
            'A',
            radius,
            radius,
            0,
            t >= 180 + this.props.angle / 2 ? 1 : 0,
            1,
            progressX,
            progressY,
        ].join(' ')

        return (
            <View style={styles.wrapper}>
                <Svg
                    style={{ position: 'absolute', top: 0, left: 0  }}
                    width={width}
                    height={height}
                >
                    <Path
                        d={circleDescriptions}
                        fill={'none'}
                        stroke={outArcColor}
                        strokeWidth={strokeWidth}
                        strokeLinecap={'round'}
                    />
                </Svg>

                <Androw style={styles.shadow}>
                    <Svg
                        width={width}
                        height={height}
                    >
                        <Path
                            d={progressDescription}
                            fill={'none'}
                            stroke={progressColor}
                            strokeWidth={progressStrokeWidth}
                            strokeLinecap={'round'}
                        />
                        <Circle
                            cx={progressX}
                            cy={progressY}
                            r={dotRadius}
                            fill={dotColor}
                        />
                    </Svg>
                </Androw>

                <View style={{ ...styles.childWrapper, width: width - strokeWidth * 4, height, left: strokeWidth * 2 }}>
                    {children}
                </View>
            </View>
        )
    }
}
```

**Comment by msand** [comment]
Can you provide a complete reproduction? Almost impossible to know otherwise.

**Comment by msand** [comment]
Closing until full reproduction is provided.

**Comment by monkeyK1n9** [comment]
I am having the same issue. Is this already resolved?
