### ISSUE TITLE
Android: Images don't render in release mode

### ISSUE THREAD

**Issue by silverspace** [react-native-community/react-native-svg#129]
I am currently experiencing an issue where Image elements render fine in development mode (when the images are vended by the npm packager), but fail to load in a release apk on android. 

I believe this is because in release mode the assets are returned by a resource identifier rather than the local relative file path, and have the form "assets_awesomemodule_icon". See the comment for resourceIdentifierWithoutScale() in https://github.com/facebook/react-native/blob/master/Libraries/Image/AssetSourceResolver.js

Tested on react-native-svg 4.1.3 with react-native 0.31.0

For reference, my stack trace for the error is:
W/unknown:React: RNSVG: fetchDecodedImage failed!
                                                java.lang.RuntimeException: Unsupported uri scheme! Uri is: react_components_images_grid
                                                    at com.facebook.imagepipeline.core.ProducerSequenceFactory.getBasicDecodedImageSequence(ProducerSequenceFactory.java:189)
                                                    at com.facebook.imagepipeline.core.ProducerSequenceFactory.getDecodedImageProducerSequence(ProducerSequenceFactory.java:142)
                                                    at com.facebook.imagepipeline.core.ImagePipeline.fetchDecodedImage(ImagePipeline.java:190)
                                                    at com.horcrux.svg.RNSVGImageShadowNode.loadBitmap(RNSVGImageShadowNode.java:128)
                                                    at com.horcrux.svg.RNSVGImageShadowNode.draw(RNSVGImageShadowNode.java:122)
                                                    at com.horcrux.svg.RNSVGGroupShadowNode.draw(RNSVGGroupShadowNode.java:46)
                                                    at com.horcrux.svg.RNSVGGroupShadowNode.draw(RNSVGGroupShadowNode.java:46)
                                                    at com.horcrux.svg.RNSVGViewBoxShadowNode.draw(RNSVGViewBoxShadowNode.java:91)
                                                    at com.horcrux.svg.RNSVGSvgViewShadowNode.drawChildren(RNSVGSvgViewShadowNode.java:84)
                                                    at com.horcrux.svg.RNSVGSvgViewShadowNode.drawOutput(RNSVGSvgViewShadowNode.java:52)
                                                    at com.horcrux.svg.RNSVGSvgViewShadowNode.onCollectExtraUpdates(RNSVGSvgViewShadowNode.java:41)
                                                    at com.facebook.react.uimanager.ReactShadowNode.dispatchUpdates(ReactShadowNode.java:200)
                                                    at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:769)

Note: My image href is loaded via:  require("./images/grid.png") and the js file is in react/components, which is where the react_components_images_grid string comes from.

**Comment by pokerman79** [comment]
did you managed to resolve this ?

Experiencing same behaviour with react-native-svg@5.1.7

**Comment by orenklein** [comment]
Same is happening over here

**Comment by talarari** [comment]
+1

**Comment by silverspace** [comment]
Unfortunately no, I implemented a workaround by rendering my SVG on top of a RN <Image>. (My use case was just a background image).

**Comment by alonbardavid** [comment]
Right now I'm solving it by using the data uri instead of an image. Works in both debug and release mode. Though for some reason, it takes a while to load the image at first.

**Comment by jlo1** [comment]
+1. @magicismight any plans to fix this? Thanks!

**Comment by Cretezy** [comment]
@alonbardavid may you show an example?

**Comment by msand** [comment]
This should be fixed at this point. Closing for now. Re-open if you still have issues with the latest version.

**Comment by Subway19** [comment]
Any idea to solve this? I am rendering Image from react-native-svg inside <Svg> ? The images work fine in  debug mode but doesnt work in release mode. The images are .png file

Below is the code .

```
<Svg width={50} height={50} style={{justifyContent : 'center', alignSelf : 'center'}}>
	<Circle cx={24} cy={24} r={24} fill='rgba(0,0,0,0.09)'/>
  <ImageSVG
                x="8"
                y="4"
                width="30"
                height="30"
                opacity="0.5"
                href={'./a.png'}
              />
</Svg>
```

**Comment by josumonk** [comment]
"react-native-svg": "^15.3.0",
Still happening

**Comment by grifotv** [comment]
I have this issue with version 15.7.1. It shows fine in debug mode but in release mode it's blank. I'm rendering a `SvgUri`:
```
import imageSource from './assets/image.svg';

const image = Image.resolveAssetSource(imageSource);

<View style={{ aspectRatio: image.width / image.height, height: 200 }}>
  <SvgUri uri={image.uri} />
</View>
```
