### ISSUE TITLE
App Crashes on Using Marker in Android (Working perfect in ios)

### ISSUE THREAD

**Issue by vaibsshukla** [react-native-community/react-native-svg#1459]
I have created Circlar arc with arrow at end in android app crahses but in ios app works perfect View is Properly Rendered. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error I am Getting 

2020-09-22 01:53:40.651 16782-16782/com.nineapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nineapp, PID: 16782
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
        at com.horcrux.svg.RNSVGMarkerPosition.ExtractPathElementFeatures(RNSVGMarkerPosition.java:131)
        at com.horcrux.svg.RNSVGMarkerPosition.UpdateFromPathElement(RNSVGMarkerPosition.java:159)
        at com.horcrux.svg.RNSVGMarkerPosition.fromPath(RNSVGMarkerPosition.java:61)
        at com.horcrux.svg.RenderableView.renderMarkers(RenderableView.java:395)
        at com.horcrux.svg.RenderableView.draw(RenderableView.java:386)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:338)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:104)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:338)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:323)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:274)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:125)
        at android.view.View.draw(View.java:20332)
        at android.view.View.updateDisplayListIfDirty(View.java:19172)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:20340)
        at android.view.View.updateDisplayListIfDirty(View.java:19172)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19163)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at android.view.View.draw(View.java:20340)
        at android.widget.ScrollView.draw(ScrollView.java:1739)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:451)
        at android.view.View.updateDisplayListIfDirty(View.java:19172)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19163)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19163)
        at android.view.View.draw(View.java:20045)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4393)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4172)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.updateDisplayListIfDirty(View.java:19163)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
2020-09-22 01:53:40.653 16782-16782/com.nineapp E/AndroidRuntime:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4377)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4350)
        at android.view.View.updateDisplayListIfDirty(View.java:19122)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3482)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3282)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2636)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1553)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7538)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1009)
        at android.view.Choreographer.doCallbacks(Choreographer.java:779)
        at android.view.Choreographer.doFrame(Choreographer.java:708)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:235)
        at android.app.ActivityThread.main(ActivityThread.java:6760)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2020-09-22 01:53:40.929 950-7580/? W/ActivityManager:   Force finishing activity com.nineapp/.MainActivity

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Here is My Code 👍 

`import * as React from "react";
import { Dimensions, StyleSheet } from "react-native";
import Svg, {
    Defs, LinearGradient, Stop, Path, Marker, Text
} from "react-native-svg";
import Animated from "react-native-reanimated";

const { interpolate, multiply } = Animated;
const { width } = Dimensions.get("window");
const size = width - 100;
const strokeWidth = 10;
const AnimatedPath = Animated.createAnimatedComponent(Path);
const { PI, cos, sin } = Math;
const r = (size - strokeWidth) / 6;
const cx = (size / 2) + size * 0.01;
const cy = size / 2 + size * 0.13
const A = PI + PI * 0.8;
const startAngle = PI + PI * 0.35;
const endAngle = 2 * PI - PI * 0.35;
// A rx ry x-axis-rotation large-arc-flag sweep-flag x y
const x1 = cx - r * cos(startAngle);
const y1 = -r * sin(startAngle);
const x2 = cx - r * cos(endAngle);
const y2 = -r * sin(endAngle);
const d = `M ${x1} ${y1} A ${r} ${r} 0 1 1 ${x2} ${y2}`;

interface CircularPogressProps {
    progress: Animated.Value<number>;
}

export default ({ progress, progressTextDataLine1, progressColorFilled, progressColorEmpty, triangleColorFilled, triangleColorEmpty }: CircularPogressProps) => {
    const circumference = r * A;
    const α = progress
    const strokeDashoffset = multiply(α, r);
    return (
        <Svg width={size} height={size / 2} >
            <Defs>
                <LinearGradient id="grad" x1="0" y1="0" x2="100%" y2="0">
                    {/* <Stop offset="0" stopColor="#f7cd46" /> */}
                    <Stop offset="1" stopColor={progressColorFilled != undefined ? progressColorFilled : "#60B244"} />

                </LinearGradient>
                <Marker
                    id="Triangle"
                    viewBox="0 0 15 15"
                    refX="0"
                    refY="5"
                    markerWidth="3"
                    markerHeight="3"
                    orient="auto"
                    markerUnits="strokeWidth"
                    stroke={'#D9D9D9'}

                >
                    {α != 0 && <Path d="M 0 0 L 4 5 L 0 10 z" stroke={'#D9D9D9'} fill={'#D9D9D9'} strokeLinejoin="round" strokeWidth={1}
                    />}
                    {α == 0 && <Path d="M 0 0 L 4 5 L 0 10 z" stroke={'#D9D9D9'} fill={'#D9D9D9'} strokeLinejoin="round" strokeWidth={1}
                    />}
                </Marker>
            </Defs>

            <Path
                markerEnd="url(#Triangle)"
                stroke={progressColorEmpty != undefined ? progressColorEmpty : '#D9D9D9'}
                fill="none"
                strokeLinejoin="round"
                strokeDasharray={`${circumference}, ${circumference}`}
                {...{ d, strokeWidth }}
            />
            <AnimatedPath
                markerEnd="url(#Triangle)"
                stroke="url(#grad)"
                fill="none"
                strokeLinejoin="round"
                strokeDasharray={`${circumference}, ${circumference}`}
                {...{ d, strokeDashoffset, strokeWidth }}
            />
            <Text
                stroke="purple"
                fontSize="20"
                x={x1 - size * 0.07}
                y={y1 + size * 0.13}
                textAnchor="middle"
                fill="red">
                {progressTextDataLine1}
            </Text>
            <Text
                stroke="purple"
                fontSize="14"
                x={x1 - size * 0.07}
                y={y1 + size * 0.19}
                textAnchor="middle"
                fill="red">

                {progressTextDataLine1 > 1 ? "Days" : 'Day'}
            </Text>
        </Svg >
    );
};


`

**Comment by WoLewicki** [comment]
Can you provide a simple reproduction of the issue? Also, is it still a problem on the newest version of the library?

**Comment by l1yefeng** [comment]
```ts
const d = `M ${x1} ${y1} A ${r} ${r} 0 1 1 ${x2} ${y2}`;
```

I get the same crash when having a similar `d` value in a path element.

```
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
        at com.horcrux.svg.RNSVGMarkerPosition.ExtractPathElementFeatures(RNSVGMarkerPosition.java:126)
```

**Comment by l1yefeng** [comment]
https://github.com/software-mansion/react-native-svg/blob/68a80c3a0bea17c8263ff6ba25000cd277b4ae16/android/src/main/java/com/horcrux/svg/PathParser.java#L446-L448

This is adding only one point to the `PathElement`.
