### ISSUE TITLE
TypeError: UIManager.createView is not a function

### ISSUE THREAD

**Issue by Igor1201** [react-native-community/react-native-svg#256]
This error appears on terminal on`jest` tests while snapshot testing  a component which contains a `Svg` with a simple subcomponent.
```
 FAIL  src/__tests__/balance.js
  ● renders view correctly

    TypeError: UIManager.createView is not a function

      at Constructor.mountComponent (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeBaseComponent.js:201:11)
      at Object.ReactReconciler.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponent.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponent.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:258:21)
      at Object.ReactReconciler.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
      at ReactTestComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react-test-renderer/lib/ReactMultiChild.js:238:44)
      at ReactTestComponent.mountComponent (node_modules/react-test-renderer/lib/ReactTestRenderer.js:62:10)

  ✕ renders view correctly (11ms)
```

Minimal test case:
```jsx
import {View} from 'react-native';
import Svg, { Polyline } from 'react-native-svg';
import React from 'react';
import renderer from 'react-test-renderer'; // Note: test renderer must be required after react-native.

it('renders view correctly', () => {
  renderer.create(
    <View>
      <Svg>
        <Polyline points='0,0 300,200' />
      </Svg>
    </View>
  ).toJSON();
});
```

Mocking `Svg` "solves" this, but I wouldn't be able to snapshot test it correctly.

**Comment by AlbertBrand** [comment]
The error is somewhat cryptic but it means that components are actually trying to create views in a test. That's not possible (and probably not what you want) when you're using the test-renderer.

You need to mock all svg elements you want to snapshot-test with something that is a good representation of the element. For instance, just an element with the provided props.

What you probably want to do is create a manual mock for the `react-native-svg` module.
You can do this by creating a `__mocks__` directory next to your `node_modules` directory and create a file called `react-native-svg.js`. In this file you place the mocked behavior of the svg module, for example:
```jsx
import React from 'react';

function createMock(elementName) {
  return (props) => React.createElement(elementName, props, props.children);
}

export const Svg = createMock('Svg');
export default Svg;

export const G = createMock('G');
export const Text = createMock('Text');
export const Line = createMock('Line');
export const Rect = createMock('Rect');
export const Path = createMock('Path');
export const Circle = createMock('Circle');
export const Polygon = createMock('Polygon');
export const Polyline = createMock('Polyline');
// ... any other svg components you use

```
This creates renderable elements without any behaviour.

Then you actually can do:
```jsx
const tree = renderer.create(
    <View>
      <Svg>
        <Polyline points='0,0 300,200' />
      </Svg>
    </View>
);
expect(tree).toMatchSnapshot();
```
and get an actual snapshot (which is exactly the test input). But you can then also render components with children that render svg elements, and snapshot how the entire tree looks like (what you probably want).

**Comment by Igor1201** [comment]
Wow, that's awesome, exactly what I was looking for!
Thank you very much for the immaculate explanation!
