### ISSUE TITLE
Crash on Android API 16(4.1.2)

### ISSUE THREAD

**Issue by lostaloneesk** [react-native-community/react-native-svg#281]
This is crash report
```
Caused by: java.lang.NullPointerException
    at android.graphics.RectF.<init>(RectF.java:76)
    at com.horcrux.svg.Brush.getPaintRect(Brush.java:79)
    at com.horcrux.svg.Brush.setupPaint(Brush.java:94)
    at com.horcrux.svg.RenderableShadowNode.setupPaint(RenderableShadowNode.java:273)
    at com.horcrux.svg.RenderableShadowNode.setupFillPaint(RenderableShadowNode.java:226)
    at com.horcrux.svg.RenderableShadowNode.draw(RenderableShadowNode.java:208)
    at com.horcrux.svg.SvgViewShadowNode.drawChildren(SvgViewShadowNode.java:147)
    at com.horcrux.svg.SvgViewShadowNode.drawOutput(SvgViewShadowNode.java:119)
    at com.horcrux.svg.SvgViewShadowNode.onCollectExtraUpdates(SvgViewShadowNode.java:103)
```

The RectF constructor source code on the android version of 16
```
public RectF(Rect r) {
        left = r.left;
        top = r.top;
        right = r.right;
        bottom = r.bottom;
 }
```

The RectF constructor source code on the android version of 17
```
public RectF(Rect r) {
       if (r == null) {
            left = top = right = bottom = 0.0f;
        } else {
            left = r.left;
            top = r.top;
            right = r.right;
            bottom = r.bottom;
        }
 }
```

**Comment by ryanhomer** [comment]
I'm getting a similar crash but `RectF` doesn't seem to be involved. This happens when I try to draw a `Line` with a `LinearGradient`.

Works fine on API 23.
Crashes on API 26.

```
java.lang.IllegalArgumentException
at android.graphics.LinearGradient.nativeCreate1(Native Method)
at android.graphics.LinearGradient.createNativeInstance(LinearGradient.java:105)
at android.graphics.Shader.getNativeInstance(Shader.java:160)
at android.graphics.Paint.getNativeInstance(Paint.java:649)
at android.graphics.BaseCanvas.drawPath(BaseCanvas.java:298)
at android.graphics.Canvas.drawPath(Canvas.java:1652)
at com.horcrux.svg.RenderableShadowNode.draw(RenderableShadowNode.java:213)
```

**Comment by msand** [comment]
Please provide a full replication. Closing until then.
