### ISSUE TITLE
Duplicate module name

### ISSUE THREAD

**Issue by IAmMarcellus** [react-native-community/react-native-svg#378]
Using results in:

`Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: D:\NightScene\NightScene\node_modules\react-native-svg\node_modules\react-native\package.json collides with D:\NightScene\NightScene\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: D:\NightScene\NightScene\node_modules\react-native-svg\node_modules\react-native\package.json collides with D:\NightScene\NightScene\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (D:/NightScene/NightScene/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (D:/NightScene/NightScene/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
Press any key to continue . . .`

**Comment by IAmMarcellus** [comment]
Nevermind, versioning incompatability
