### ISSUE TITLE
Bunch of crashes on Android (6.x and 7.x) - strokeDashoffset and strokeWidth

### ISSUE THREAD

**Issue by jabajaj** [react-native-community/react-native-svg#489]
We are seeing a bunch of crashes on Android originating from react-native-svg. I'm a little confused about the exact source of this crash as we never set 'strokeDashoffset' anywhere in our react native views. There's also a similar crash with the proprety 'strokeWidth' (which we also never set explicitly).  Could anyone help with some pointers on fixing this (or at least determining the root cause)?

This are the stack traces I have: 

## strokeDashoffset:
`com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'strokeDashoffset' in shadow node of type: RNSVGPath
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
	at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:272)
	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:197)
	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:241)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: method com.horcrux.svg.RenderableShadowNode.setStrokeDashoffset argument 1 has type float, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:105)
	... 15 more`

## strokeWidth:
`com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'strokeWidth' in shadow node of type: RNSVGPath
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
	at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:272)
	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:197)
	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:249)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.IllegalArgumentException: method com.horcrux.svg.RenderableShadowNode.setStrokeWidth argument 1 has type float, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:105)
	... 15 more`

Thanks!

**Comment by msand** [comment]
What versions or react, react-native and react-native-svg are you using?

**Comment by jabajaj** [comment]
"react": "16.0.0-rc.2",
    "react-native": "0.47.1",
    "react-native-svg": "5.4.1"

**Comment by cihantas** [comment]
Same problem.

`
"react": "16.0.0-alpha.12",
"react-native": "^0.48.4",
"react-native-svg": "^6.0.0-rc1",
`

**Comment by lizouzt** [comment]
Same.
```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
```

**Comment by cihantas** [comment]
@lizouzt @msand @jabajaj Are you using Expo? Have you tried running it without Expo?

**Comment by lizouzt** [comment]
@cihantas Not used it

**Comment by msand** [comment]
Haven't used it en Expo, only without it. Can you make a minimal replication repo using the latest versions of react-native init and react-native-svg?

**Comment by yanniser** [comment]
same problem 

    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-svg": "6.0.0"

**Comment by pveyes** [comment]
I also got this problem when using Expo SDK 23 and `react-native-svg@6.0.0`. Turns out the solution is simple, just uninstall `react-native-svg`, expo already bundled `react-native-svg` so we don't need to install it manually

**Comment by jabajaj** [comment]
@pveyes we're not using the expo SDK.

**Comment by msand** [comment]
@jabajaj Are you still having this issue? Can you try with v6.1.0?

**Comment by msand** [comment]
Make sure you've rebuild the native bundle after upgrading react-native-svg, this is probably caused by not doing that.

**Comment by jabajaj** [comment]
I was definitely rebuilding the native bundle after upgrading. I _think_ what resolved the issue is the fact that we now only have one instance of the ReactInstanceManager vs. multiple instances before.
