### ISSUE TITLE
elliptical text leads to error "out of range in dynamic array"

### ISSUE THREAD

**Issue by nico1510** [react-native-community/react-native-svg#496]
I'm trying to align Text on an elliptic path more or less like in the README examples. Here's the code:
```javascript
const Test = ({ width, height }) => {
        const path = "M 55 85 a129 59 0 1 1 0 5";
        return (
                <Svg height={170} width={370}>
                    <Defs>
                        <Path
                            id="path"
                            d={path}
                        />
                    </Defs>
                    <Text fill="blue">
                        <TextPath href="#path">United States of America</TextPath>
                    </Text>
                </Svg>
        );
    }
```
I get the following StackTrace: 
```
java.lang.ArrayIndexOutOfBoundsException: out of range in dynamic array
at com.facebook.react.bridge.ReadableNativeArray.getArray(Native Method)
at com.facebook.react.bridge.ReadableNativeArray.getArray(ReadableNativeArray.java:21)
at com.horcrux.svg.BezierTransformer.setControlPoints(BezierTransformer.java:88)
at com.horcrux.svg.BezierTransformer.setControlPoints(BezierTransformer.java:94)
at com.horcrux.svg.BezierTransformer.getTransformAtDistance(BezierTransformer.java:129)
at com.horcrux.svg.TSpanShadowNode.getLinePath(TSpanShadowNode.java:108)
at com.horcrux.svg.TSpanShadowNode.getPath(TSpanShadowNode.java:81)
at com.horcrux.svg.GroupShadowNode$2.run(GroupShadowNode.java:72)
at com.horcrux.svg.VirtualNode.traverseChildren(VirtualNode.java:246)
at com.horcrux.svg.GroupShadowNode.getPath(GroupShadowNode.java:70)
at com.horcrux.svg.TextShadowNode.getGroupPath(TextShadowNode.java:177)
at com.horcrux.svg.TextPathShadowNode.getPath(TextPathShadowNode.java:60)
at com.horcrux.svg.GroupShadowNode$2.run(GroupShadowNode.java:72)
at com.horcrux.svg.VirtualNode.traverseChildren(VirtualNode.java:246)
at com.horcrux.svg.GroupShadowNode.getPath(GroupShadowNode.java:70)
at com.horcrux.svg.TextShadowNode.getGroupPath(TextShadowNode.java:177)
at com.horcrux.svg.TextShadowNode.draw(TextShadowNode.java:92)
at com.horcrux.svg.SvgViewShadowNode.drawChildren(SvgViewShadowNode.java:147)
at com.horcrux.svg.SvgViewShadowNode.drawOutput(SvgViewShadowNode.java:119)
at com.horcrux.svg.SvgViewShadowNode.onCollectExtraUpdates(SvgViewShadowNode.java:103)
at com.facebook.react.uimanager.ReactShadowNode.dispatchUpdates(ReactShadowNode.java:300)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:866)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:857)
at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:604)
at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:570)
at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:531)
at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:136)
at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:143)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:
```

**Comment by nico1510** [comment]
I just tried with version 6.0.0 and it works
