### ISSUE TITLE
Caused by: java.lang.NumberFormatException: Invalid float: "N"

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-svg#523]
it only happens on release mode

```jsx
[E/AndroidRuntime(31017): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime(31017): Process: net.natura.fv, PID: 31017
E/AndroidRuntime(31017): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' in shadow node of type: RNSVGPath
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:298)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.UIImplementation.updateView(UIImplementation.java:309)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.UIManagerModule.updateView(UIManagerModule.java:372)
E/AndroidRuntime(31017): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31017): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31017): 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
E/AndroidRuntime(31017): 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
E/AndroidRuntime(31017): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime(31017): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(31017): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(31017): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime(31017): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(31017): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
E/AndroidRuntime(31017): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(31017): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(31017): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31017): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31017): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
E/AndroidRuntime(31017): 	... 16 more
E/AndroidRuntime(31017): Caused by: java.lang.NumberFormatException: Invalid float: "N"
E/AndroidRuntime(31017): 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
E/AndroidRuntime(31017): 	at java.lang.StringToReal.parseName(StringToReal.java:249)
E/AndroidRuntime(31017): 	at java.lang.StringToReal.parseFloat(StringToReal.java:314)
E/AndroidRuntime(31017): 	at java.lang.Float.parseFloat(Float.java:306)
E/AndroidRuntime(31017): 	at com.horcrux.svg.PropHelper$PathParser.getNextFloat(PropHelper.java:329)
E/AndroidRuntime(31017): 	at com.horcrux.svg.PropHelper$PathParser.executeCommand(PropHelper.java:209)
E/AndroidRuntime(31017): 	at com.horcrux.svg.PropHelper$PathParser.getPath(PropHelper.java:294)
E/AndroidRuntime(31017): 	at com.horcrux.svg.PathShadowNode.setD(PathShadowNode.java:28)
E/AndroidRuntime(31017): 	... 19 more](`url`)
```

**Comment by sibelius** [comment]
if you pass `null` do `d` it will show this cryptic error
