### ISSUE TITLE
Error while updating property 'd' in shadow node of type: RNSVGPath - null for input string: "N"

### ISSUE THREAD

**Issue by bjornbrynjar** [react-native-community/react-native-svg#542]
Got really strange problem here.  The problem doesn't exists when I use react-native 'Debug JS remotely'.  However when I run the code normally I get the following error:

![screenshot_2017-12-11-23-27-15-995_com easeapp debug](https://user-images.githubusercontent.com/10855937/33915104-7059ba82-df99-11e7-91da-ab237ae6ac10.png)

I have double checked the float values that are being rendered, no null values do exists. The float values are in the form:  5.388888835906982. 

 Here is the code rendering the line:
`buildLinePlot (data, view, trbl, xScale, yScale) {
    let bgline = line()
      .x(function(x){
        return xScale(new Date(x.measured));
	    })
      .y(function(y){
        return yScale(y.glucose.value);
	    }).
      curve(curveCardinal.tension(0.0));
    return (
        <Path d={bgline(data)}
        fill='none'
        stroke= {Constants.TANGERINE}
        strokeWidth={2}
        zIndex='100'/>
    );
  }`

Here is the stacktrace:
'com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' in shadow node of type: RNSVGPath
at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:298)
at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:373)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:754)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:163)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
... 15 more
Caused by: java.lang.NumberFormatException: For input string: "N"
at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
at java.lang.Float.parseFloat(Float.java:459)
at com.horcrux.svg.PropHelper$PathParser.getNextFloat(PropHelper.java:274)
at com.horcrux.svg.PropHelper$PathParser.executeCommand(PropHelper.java:146)
at com.horcrux.svg.PropHelper$PathParser.getPath(PropHelper.java:239)
at com.horcrux.svg.PathShadowNode.setD(PathShadowNode.java:30)
... 17 more'

Can you see what is causing this?

**Comment by bjornbrynjar** [comment]
Seems I been able to get around the problem, not sure the root cause was found! 

I noticed the date format I was reading from my database for the y - value was incorrect. 
"2017-12-13 23:24:34.234"  instead of "2017-12-13T23:24:34.234Z" 

Once fixed, the problem is gone.   I was sure the problem was with the Floating point value, as the stacktrace indicated Floating point - NumberFormatException.

Anyway thanks!
