### ISSUE TITLE
Unexpected view type nested under text node: class com.horcrux.svg.SvgViewShadowNode

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-svg#619]
can we improve the error in this case?

```
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: com.facebook.react.uimanager.IllegalViewOperationException: Unexpected view type nested under text node: class com.horcrux.svg.SvgViewShadowNode
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.views.text.ReactBaseTextShadowNode.buildSpannedFromShadowNode(ReactBaseTextShadowNode.java:108)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.views.text.ReactBaseTextShadowNode.spannedFromShadowNode(ReactBaseTextShadowNode.java:175)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.views.text.ReactTextShadowNode.onBeforeLayout(ReactTextShadowNode.java:162)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:933)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:931)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:689)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:654)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:663)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:136)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:145)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:789)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:164)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-06 17:57:00.468  4244  4604 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
03-06 17:57:00.501  4244  4604 I chatty  : uid=10085(u0_a85) mqt_native_modu identical 8 lines
```

**Comment by msand** [comment]
Well, it's thrown by react-native, so would have to ask them. I'm not sure what would be a more accurate message though.
https://github.com/facebook/react-native/blob/5898817fc1a66bd317d65ce96520159df2f96045/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java#L106
