### ISSUE TITLE
 SurfaceView should have explicit width and height set

### ISSUE THREAD

**Issue by habeebrahmanpt** [react-native-community/react-native-svg#687]
05-14 18:42:51.366 6017-11115/com.alliance E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: SurfaceView should have explicit width and height set
        at com.horcrux.svg.SvgViewManager$1.measure(SvgViewManager.java:39)
        at com.facebook.yoga.YogaNode.measure(YogaNode.java:654)
        at com.facebook.yoga.YogaNode.jni_YGNodeCalculateLayout(Native Method)
        at com.facebook.yoga.YogaNode.calculateLayout(YogaNode.java:198)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:512)
        at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:942)
        at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:694)
        at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:654)
        at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:665)
        at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:134)
        at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:145)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)

**Comment by melihberberolu** [comment]
@habeebrahmanpt  Any solution ?

**Comment by melihberberolu** [comment]
Wrap all svgs in View component and set height and width.

**Comment by NiuYangYang** [comment]
为什么Android不能像iOS那样动态设置高度？

**Comment by ericjames** [comment]
SVG requires explicitly numeral values in Android while iOS can deal with percentages or other values gracefully.  React is just giving us the default native behavior of Android to fail critically so I don't see a fix here unless React wants to cushion the blow.

**Comment by msand** [comment]
@ericjames Hmm, are you sure you're using the latest version? At least in my current work in progress branch https://github.com/react-native-community/react-native-svg/pull/757 percentage width and height works in both in iOS and Android.

**Comment by edoantonioco** [comment]
SVGs without being able to provide percentajes as width and height, makes it not an option for most use cases. Hopefully this gets fixed.

**Comment by msand** [comment]
@edoantonioco Try v7.0.0

**Comment by msand** [comment]
I think this is fixed in the latest version, otherwise, try the plain-views branch

**Comment by mvanroon** [comment]
@msand thanks, will do
