### ISSUE TITLE
Error on installing the package

### ISSUE THREAD

**Issue by renatobenks** [react-native-community/react-native-svg#698]
Environments
---

**OS:** macOS High Sierra, 10.13.3
**node:** v8.8.1
**npm:** 5.4.2
**yarn:** 1.6.0

Description
---

I'm trying install the `react-native-svg` by yarn, however I getting the following error:

```bash
$ yarn add react-native-svg --verbose
yarn add v1.6.0
verbose 0.581 Checking for configuration file "/Users/renatobenks/Projects/luvbook-app/.npmrc".
verbose 0.582 Checking for configuration file "/Users/renatobenks/.npmrc".
verbose 0.582 Found configuration file "/Users/renatobenks/.npmrc".
verbose 0.582 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.583 Checking for configuration file "/Users/renatobenks/Projects/luvbook-app/.npmrc".
verbose 0.583 Checking for configuration file "/Users/renatobenks/Projects/.npmrc".
verbose 0.583 Checking for configuration file "/Users/renatobenks/.npmrc".
verbose 0.584 Found configuration file "/Users/renatobenks/.npmrc".
verbose 0.584 Checking for configuration file "/Users/.npmrc".
verbose 0.587 Checking for configuration file "/Users/renatobenks/Projects/luvbook-app/.yarnrc".
verbose 0.587 Checking for configuration file "/Users/renatobenks/.yarnrc".
verbose 0.587 Found configuration file "/Users/renatobenks/.yarnrc".
verbose 0.588 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.588 Checking for configuration file "/Users/renatobenks/Projects/luvbook-app/.yarnrc".
verbose 0.588 Checking for configuration file "/Users/renatobenks/Projects/.yarnrc".
verbose 0.588 Checking for configuration file "/Users/renatobenks/.yarnrc".
verbose 0.589 Found configuration file "/Users/renatobenks/.yarnrc".
verbose 0.589 Checking for configuration file "/Users/.yarnrc".
verbose 0.594 current time: 2018-05-26T00:48:25.626Z
[1/4] 🔍  Resolving packages...
verbose 1.883 Performing "GET" request to "https://registry.yarnpkg.com/react-native-svg".
verbose 17.004 Request "https://registry.yarnpkg.com/react-native-svg" finished with status code 503.
verbose 17.009 Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:237:66)
    at new MessageError (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:266:123)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:51665:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:23469:28)
    at Function.<anonymous> (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/usr/local/Cellar/yarn/1.6.0/libexec/lib/cli.js:51707:19)
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

With npm is happening an error also, as bellow:

```bash
$ npm i react-native-svg --save
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected string or string but got null
npm ERR! typeerror     at fetchPackageMetadata (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/fetch-package-metadata.js:36:3)
npm ERR! typeerror     at limited (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/call-limit/call-limit.js:29:10)
npm ERR! typeerror     at addDependency (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/install/deps.js:549:5)
npm ERR! typeerror     at /Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/install/deps.js:482:5
npm ERR! typeerror     at /Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at loadDeps (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/install/deps.js:474:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at /Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/install/deps.js:369:5
npm ERR! typeerror     at cb (/Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! typeerror     at /Users/renatobenks/.nvm/versions/node/v8.8.1/lib/node_modules/npm/lib/install/deps.js:524:5
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/renatobenks/.npm/_logs/2018-05-26T00_53_24_243Z-debug.log
```

**Comment by renatobenks** [comment]
It's solved, the npm/yarn was with a trouble to install this package!
