### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by NirpE** [react-native-community/react-native-svg#784]
Using library version 7.0.2 along with `victory-native` charts.

Minimum reproducing example might be difficult since the crash occurs when new screen is opened and data edited there and screen popped which causes redux update to previous screen which has the chart.

Works fine on iOS. 

> java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap com.horcrux.svg.SvgViewShadowNode.drawOutput()' on a null object reference
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:100)
        at android.view.View.draw(View.java:19192)
        at android.view.View.updateDisplayListIfDirty(View.java:18142)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
        at android.view.View.updateDisplayListIfDirty(View.java:18101)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by msand** [comment]
@NirpE Can you try replacing this line https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/SvgView.java#L100

With something like:

```java
            SvgViewShadowNode node = getShadowNode();
            if (node == null) {
                return;
            }
            mBitmap = node.drawOutput();
```

**Comment by NirpE** [comment]
@msand Forked and tried it, prevents the crash but now it doesn't render the graph anymore.

**Comment by sinhpn92** [comment]
I have same issue. have any ideal to fix it?

**Comment by NirpE** [comment]
@sinhpn92 I made a fix for it but it's waiting for pull request approval. Meanwhile you can try using this package:

"react-native-svg": "github:NirpE/react-native-svg"

**Comment by shrutigupta1195** [comment]
Still crashing

**Comment by msand** [comment]
Fix has been published, upgrade to latest version.
