### ISSUE TITLE
Android crash: Value for fill cannot be cast from ReadableNativeArray to Double

### ISSUE THREAD

**Issue by janicduplessis** [react-native-community/react-native-svg#806]
I'm seeing this crash log on Android in production since updating to ^7.0.0. I'm not sure how to reproduce locally but it comes a svg component that is animated using native animated. However I can't reproduce the crash reliably so there must be some kind of race condition.

I noticed the implementation uses shadow nodes to save the svg data but if I understand correctly it could just be normal uithread view manager props. Shadow nodes run on a different thread so it might be what causes this race condition.

Here's the full stacktrace if that can be useful, the interesting part is the inner exception.

```
JSApplicationIllegalArgumentException
Error while updating property 'bottom' in shadow node of type: RNSScreen
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp at line 116
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter in setProperty at line 157
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 61
com.facebook.react.uimanager.ReactShadowNodeImpl in updateProperties at line 458
com.facebook.react.uimanager.UIImplementation in createView at line 295
com.facebook.react.uimanager.UIManagerModule in createView at line 383
java.lang.reflect.Method in invoke
com.facebook.react.bridge.JavaMethodWrapper in invoke at line 372
com.facebook.react.bridge.JavaModuleWrapper in invoke at line 158
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 789
android.os.Handler in dispatchMessage at line 98
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 29
android.os.Looper in loop at line 164
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3 in run at line 192
java.lang.Thread in run at line 764
InvocationTargetException
java.lang.reflect.Method in invoke
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp at line 110
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter in setProperty at line 157
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 61
com.facebook.react.uimanager.ReactShadowNodeImpl in updateProperties at line 458
com.facebook.react.uimanager.UIImplementation in createView at line 295
com.facebook.react.uimanager.UIManagerModule in createView at line 383
java.lang.reflect.Method in invoke
com.facebook.react.bridge.JavaMethodWrapper in invoke at line 372
com.facebook.react.bridge.JavaModuleWrapper in invoke at line 158
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 789
android.os.Handler in dispatchMessage at line 98
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 29
android.os.Looper in loop at line 164
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3 in run at line 192
java.lang.Thread in run at line 764
== INNER EXCEPTION ==
ClassCastException
Value for fill cannot be cast from ReadableNativeArray to Double
com.facebook.react.bridge.ReadableNativeMap in checkInstance at line 148
com.facebook.react.bridge.ReadableNativeMap in getValue at line 127
com.facebook.react.bridge.ReadableNativeMap in getDouble at line 168
com.facebook.react.bridge.DynamicFromMap in asDouble at line 64
com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue in setFromDynamic at line 67
com.facebook.react.uimanager.LayoutShadowNode in setPositionValues at line 699
java.lang.reflect.Method in invoke
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateShadowNodeProp at line 110
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter in setProperty at line 157
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 61
com.facebook.react.uimanager.ReactShadowNodeImpl in updateProperties at line 458
com.facebook.react.uimanager.UIImplementation in createView at line 295
com.facebook.react.uimanager.UIManagerModule in createView at line 383
java.lang.reflect.Method in invoke
com.facebook.react.bridge.JavaMethodWrapper in invoke at line 372
com.facebook.react.bridge.JavaModuleWrapper in invoke at line 158
com.facebook.react.bridge.queue.NativeRunnable in run
android.os.Handler in handleCallback at line 789
android.os.Handler in dispatchMessage at line 98
com.facebook.react.bridge.queue.MessageQueueThreadHandler in dispatchMessage at line 29
android.os.Looper in loop at line 164
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3 in run at line 192
java.lang.Thread in run at line 764
```

**Comment by msand** [comment]
I wonder if it could be related to this: https://github.com/react-native-community/react-native-svg/commit/c39b3267f1b970112fd96a5608ad2cec931ac277
Because this probably changed on what thread the rendering is done.

But, it seems more like the ViewManagerPropertyUpdater uses an incorrect FallbackShadowNodeSetter to set the fill property, somehow it seems to confuse the fill property with a MutableYogaValue and calls LayoutShadowNode.setPositionValues on it, which leads to this line: https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/LayoutShadowNode.java#L65

It seems to be missing a check for the number type before calling dynamic.asDouble() 
 ```java
      else if (dynamic.getType() == ReadableType.Number) {
        unit = YogaUnit.POINT;
        value = PixelUtil.toPixelFromDIP(dynamic.asDouble());
      }
```
https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/LayoutShadowNode.java#L67

I wonder why it doesn't use the setter from the view manager:
https://github.com/react-native-community/react-native-svg/blob/v7.0.3/android/src/main/java/com/horcrux/svg/RenderableViewManager.java#L707

and the shadow node:
https://github.com/react-native-community/react-native-svg/blob/v7.0.3/android/src/main/java/com/horcrux/svg/RenderableViewManager.java#L705

Tricky to analyse without a reproduction.

**Comment by msand** [comment]
Currently, the Views on Android are only used to get access to the shadow nodes for native animation: https://github.com/react-native-community/react-native-svg/blob/master/android/src/main/java/com/horcrux/svg/RenderableView.java#L8
Essentially all the data and logic is in the shadow nodes for now. Only the svg root has a View which gets attached to the render tree, and it only renders lazily (by calling into the shadow node) and caches the bitmap until the next invalidation. I suspect this might cause some race conditions, if the shadow nodes / trees are  modified, while the svg root is rendering the bitmap.

**Comment by janicduplessis** [comment]
Actually I think there might be 2 separate issues. I linked the wrong stacktrace in the initial issue. Here’s the one that seems to be related to the race condition I was talking about. 

```
JSApplicationIllegalArgumentException
Error while updating property 'stroke' of a view managed by: RNSVGRect
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateViewProp at line 95
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter in setProperty at line 132
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 51
com.facebook.react.uimanager.ViewManager in updateProperties at line 34
com.facebook.react.uimanager.NativeViewHierarchyManager in createView at line 269
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation in execute at line 200
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in dispatchPendingNonBatchedOperations at line 1105
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in doFrameGuarded at line 1076
com.facebook.react.uimanager.GuardedFrameCallback in doFrame at line 29
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher in doFrame at line 134
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1 in doFrame at line 105
android.view.Choreographer$CallbackRecord in run at line 869
android.view.Choreographer in doCallbacks at line 683
android.view.Choreographer in doFrame at line 616
android.view.Choreographer$FrameDisplayEventReceiver in run at line 857
android.os.Handler in handleCallback at line 751
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 154
android.app.ActivityThread in main at line 6154
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 867
com.android.internal.os.ZygoteInit in main at line 757
InvocationTargetException
java.lang.reflect.Method in invoke
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateViewProp at line 83
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter in setProperty at line 132
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 51
com.facebook.react.uimanager.ViewManager in updateProperties at line 34
com.facebook.react.uimanager.NativeViewHierarchyManager in createView at line 269
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation in execute at line 200
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in dispatchPendingNonBatchedOperations at line 1105
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in doFrameGuarded at line 1076
com.facebook.react.uimanager.GuardedFrameCallback in doFrame at line 29
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher in doFrame at line 134
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1 in doFrame at line 105
android.view.Choreographer$CallbackRecord in run at line 869
android.view.Choreographer in doCallbacks at line 683
android.view.Choreographer in doFrame at line 616
android.view.Choreographer$FrameDisplayEventReceiver in run at line 857
android.os.Handler in handleCallback at line 751
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 154
android.app.ActivityThread in main at line 6154
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 867
com.android.internal.os.ZygoteInit in main at line 757
IllegalStateException
This dynamic value has been recycled
com.facebook.react.bridge.DynamicFromMap in asString at line 78
com.horcrux.svg.RenderableShadowNode in setStroke at line 139
com.horcrux.svg.RenderableViewManager in setStroke at line 723
java.lang.reflect.Method in invoke
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter in updateViewProp at line 83
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter in setProperty at line 132
com.facebook.react.uimanager.ViewManagerPropertyUpdater in updateProps at line 51
com.facebook.react.uimanager.ViewManager in updateProperties at line 34
com.facebook.react.uimanager.NativeViewHierarchyManager in createView at line 269
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation in execute at line 200
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in dispatchPendingNonBatchedOperations at line 1105
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback in doFrameGuarded at line 1076
com.facebook.react.uimanager.GuardedFrameCallback in doFrame at line 29
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher in doFrame at line 134
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1 in doFrame at line 105
android.view.Choreographer$CallbackRecord in run at line 869
android.view.Choreographer in doCallbacks at line 683
android.view.Choreographer in doFrame at line 616
android.view.Choreographer$FrameDisplayEventReceiver in run at line 857
android.os.Handler in handleCallback at line 751
android.os.Handler in dispatchMessage at line 95
android.os.Looper in loop at line 154
android.app.ActivityThread in main at line 6154
java.lang.reflect.Method in invoke
com.android.internal.os.ZygoteInit$MethodAndArgsCaller in run at line 867
com.android.internal.os.ZygoteInit in main at line 757
```

**Comment by msand** [comment]
Thanks for this, could you try with the latest commit from the master branch?

**Comment by msand** [comment]
Could you post the code or a small reproduction that can produce it? I'm not sure how the dynamic value could be recycled, perhaps it isn't even a string? At least react-native-svg doesn't make any recycle calls on any dynamic values.

**Comment by janicduplessis** [comment]
Here's the code for the component https://gist.github.com/janicduplessis/87a859eda656806bd2dea0db0a8940f1

I'm planning a new release in the next few days, I will update to master.

**Comment by janicduplessis** [comment]
Actually I think the first crash is related to changes I made locally to try to fix the 2nd stack trace I linked. I'll update the issue to only include the `This dynamic value has been recycled` crash. Sorry about that.

**Comment by msand** [comment]
I've been testing this code for some time now and haven't been able to observe any exceptions. Not sure how to trigger it:
```jsx
// @flow

import * as React from "react";
import { Button, StyleSheet, View, Animated } from "react-native";
import Svg, { Line, Circle } from "react-native-svg";

const AnimatedLine = Animated.createAnimatedComponent(Line);
const AnimatedCircle = Animated.createAnimatedComponent(Circle);

type Props = {
  style?: any,
  backgroundIsTurquoise?: boolean,
};
type State = {
  anim: Animated.Value,
};

class Loading extends React.Component<Props, State> {
  state = {
    anim: new Animated.Value(0),
    hide: false,
  };

  componentDidMount() {
    Animated.loop(
      Animated.timing(this.state.anim, {
        duration: 2000,
        toValue: 1,
        isInteraction: false,
        useNativeDriver: true,
      }),
    ).start();
  }

  render() {
    const opacity = this.state.anim.interpolate({
      inputRange: [0, 0.93, 1],
      outputRange: [1, 1, 0],
    });
    const yellowBarOffset = this.state.anim.interpolate({
      inputRange: [0, 0.2, 1],
      outputRange: [22, 0, 0],
    });
    const greenBarOffset = this.state.anim.interpolate({
      inputRange: [0, 0.19, 0.4, 1],
      outputRange: [30.01, 30.01, 0, 0],
    });
    const pinkBarOffset = this.state.anim.interpolate({
      inputRange: [0, 0.4, 0.78, 1],
      outputRange: [107, 107, 50, 50],
    });

    const secondLineColor = this.props.backgroundIsTurquoise
      ? "white"
      : "turquoise";
    const { hide } = this.state;

    return (
      <View>
        <Button
          title="Toggle"
          onPress={() => this.setState(({ hide }) => ({ hide: !hide }))}
        />
        <Animated.View style={[{ opacity }, this.props.style]}>
          {hide ? null : (
            <Svg width={70} height={70}>
              <AnimatedLine
                stroke={secondLineColor}
                strokeWidth="8"
                strokeLinecap="round"
                strokeDasharray={[30]}
                strokeDashoffset={greenBarOffset}
                x1="48"
                y1="15"
                x2="29"
                y2="34.2"
              />
              <AnimatedCircle
                fill="transparent"
                stroke="pink"
                strokeWidth="8"
                strokeLinecap="round"
                strokeDasharray={[107]}
                strokeDashoffset={pinkBarOffset}
                rotation="-127"
                origin="36, 44"
                cx="36"
                cy="44"
                r="12"
              />
              <AnimatedLine
                stroke="yellow"
                strokeWidth="8.5"
                strokeLinecap="round"
                strokeDasharray={[22]}
                strokeDashoffset={yellowBarOffset}
                x1="26"
                y1="14.5"
                x2="48"
                y2="14.5"
              />
            </Svg>
          )}
        </Animated.View>
      </View>
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Loading />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "beige",
  },
});

```

**Comment by janicduplessis** [comment]
@msand Thanks for trying it out, I can't reproduce the issue neither on my end and it seems to happen very rarely. Hopefully we can figure something out from the stacktrace or other people hit this crash too.

**Comment by Almouro** [comment]
Hi guys,

Yesterday got ~1k crashes quite similar for about ~20k users on the app yesterday.

Crashes we are getting are usually:
- `This dynamic value has been recycled`
- `java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.Double
    at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:147)`
- and `java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
    at android.support.v4.util.Pools$SimplePool.release(Pools.java:116)
    at com.facebook.react.bridge.DynamicFromMap.recycle(DynamicFromMap.java:40)`

These are new bugs in our last release that included an upgrade (among other things of course) of `react-native-svg` from `6.5.1` to `7.3.0`.

All of those bugs seem to touch the `SimplePoll` recycling and upon investigation I found this PR https://github.com/facebook/react-native/pull/17842 which makes the `SimplePool` in `DynamicFromMap` thread safe.

Investigating with Android Studio debugger by setting breakpoints in `DynamicFromMap.create` in [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/DynamicFromMap.java#L27), I found that this method was called by 2 threads:
- `mqt_native_modules` for basic RN components
- `main` only for `react-native-svg`

I also saw that `react-native-svg` is using `Dynamic` since version 7 of the lib  (https://github.com/react-native-community/react-native-svg/commit/3879c90bd8273ba8b38713b2f39d2bdfd5265665)

So it seems like the issue could be:
- react-native-svg started using Dynamic
- but SimplePool in DynamicFromMap is not thread safe
- and react-native-svg uses a different thread than default RN one

I can try downgrading `react-native-svg` or applying the PR above and build the app with the forked React Native version to validate that.

What do you guys think? Where is `react-native-svg` using a different thread?

**Comment by Almouro** [comment]
@msand https://github.com/react-native-community/react-native-svg/commit/3879c90bd8273ba8b38713b2f39d2bdfd5265665 is rolling out for 10% of our users now.
I'll let you know how it goes :)

**Comment by Almouro** [comment]
@msand I confirm that this issue has disappeared 🎉 for those 10% including the PR on React Native (facebook/react-native#17842)
I'll push this PR on React Native side, but might I ask: why is it that other components being animated with the native driver don't trigger this exception while `react-native-svg` components do?

Our biggest crash on that newest release is now:
```
Caused by: java.lang.NullPointerException: 
  at com.horcrux.svg.RenderableViewManager$6.setR (RenderableViewManager.java:237)
```
I can open a new issue for it, I don't think it's related

**Comment by msand** [comment]
@Almouro Can you try v7.1.0 I suspect https://github.com/react-native-community/react-native-svg/commit/1e25870f5d04b91112e7167240dd1a7d4958815f to be the culprit.

**Comment by janicduplessis** [comment]
@msand Sure, I was about to also ship the PR to test if it fixes the issue but it seems like it does :)

**Comment by janicduplessis** [comment]
Native Animated does not work with layout props so its probably just those ones that use Dynamic.

**Comment by msand** [comment]
@janicduplessis Are there any drawbacks to using Dynamic? There is at least some performance penalty, because of the branching on type in the view property setters, and wrapping the JavaOnlyMap in a DynamicFromMap. But other than that, I can't see any significant differences between Dynamic and otherwise. At least from a quick reading of: 

https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/Dynamic.java

https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/DynamicFromMap.java

https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/ReactStylesDiffMap.java

https://github.com/facebook/react-native/blob/0.57-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java

**Comment by janicduplessis** [comment]
@msand AFAIK Dynamic was implemented to support props with multiple possible types like for example `style.width` can be either a number or a string when using percent units. Other than that I don't think it should be used since like you said there is a small perf hit.

**Comment by msand** [comment]
@Almouro Can you try with the latest commit from the master branch? I've simplified the dynamic property setters in android and improved the null handling logic.

**Comment by msand** [comment]
There's a potentially significant optimisation opportunity in the property handling, for any props which currently take a string to allow for units. There's a redundant round-trip from a double to a string back to a double, when animating the properties (or whenever the given value is a double / Number). The common case is probably a unit-less number anyway, so it would make sense to optimise for that. To maintain spec-conformance, it would require adding an enum for the units, another field signifying the unit for each property, and, that the property setters would handle the case when the value is a string, such that it sets the unit correctly. And finally, the relativeOnWidth/Height/Other (css units to pixels resolvers) would need to accept a number and a enum unit instead of a string.

**Comment by msand** [comment]
Another optimisation opportunity would be to rename the fields such that the propertyNameToFieldName could be removed.

**Comment by msand** [comment]
Also, as @janicduplessis wrote. The shadow nodes could be removed, by creating separate View classes and moving the logic from the shadow nodes there instead. Because the SvgViewManager returns true for needsCustomLayoutForChildren anyway, and we're already creating a View for each element (to allow for animation). So it should actually conserve memory, and possibly improve  performance as well. Or are there any benefits to having the shadow nodes I'm unaware of? As we're not using yoga for layout (except for the root svg element position and dimension) they should just be redundant, right?

**Comment by msand** [comment]
At least currently, having the shadow nodes causes an extra de-referencing for each time a property is set using the ViewManagers, and we keep a

```java
    private final SparseArray<T> mTagToShadowNode = new SparseArray<>();
```

to get a reference to it (costing memory and accounting on View creation/destruction), which wouldn't be needed if the logic was simply inside the Views instead.

**Comment by msand** [comment]
I now have a branch where I've moved the logic into the View and almost completely removed the shadow nodes. https://github.com/react-native-community/react-native-svg/commit/0bdca66e2de07bd964f917fb04d4c60b9d3c0b0e
It certainly seems to perform better.

**Comment by msand** [comment]
@msageryd Could you try your app with the latest commit from master and the one from the plain-views branch to see if there's any significant changes? https://github.com/react-native-community/react-native-svg/compare/plain-views

**Comment by Almouro** [comment]
@msand I opened a new issue for the new bug. I don't think it has to do with this issue anymore :)

**Comment by janicduplessis** [comment]
@msand I think removing shadow nodes on Android makes sense, iOS already uses views only.

**Comment by msand** [comment]
The current latest commit in the plain-views branch seems to work in all tests I have quickly testable. Don't see any reasons not to cut another release at this point. Unless you know of any regressions?
Could perhaps still do the refactoring to optimise for doubles / unitless numbers, but I'm not sure when exactly I would have time to finish that.

**Comment by msand** [comment]
@janicduplessis Would it be possible to get that PR cherrypicked for v0.57.4? Seems it should probably be the recommended minimum for any version of react-native-svg using Dynamic. And the plain views branch should probably become the recommended v7 version, to eliminate the null exceptions.

**Comment by msand** [comment]
I've implemented the optimizations in the SVGLength branch now: https://github.com/react-native-community/react-native-svg/commit/50eee0abe7004636d72776edce94b2b667469bb1
Commit msg: Optimize setting properties and animation: Implement SVGLength

Removes redundant round-trip (double > string > double) when animating.
Optimizes for the case when dynamic arguments are numbers.
Improves memory consumption and cpu load.

**Comment by msand** [comment]
The css value resolvers could still be made to get the canvas width/height and font-size only when needed, instead of every time.

**Comment by msand** [comment]
Implemented fast path for css resolvers, android: https://github.com/react-native-community/react-native-svg/commit/2a449c3bd4b2095427c35a17d81b025e5a1dd713 ios: https://github.com/react-native-community/react-native-svg/commit/00f0b66c131c88d43a4790c482bbb5e51c23f662

**Comment by msand** [comment]
I've fixed all known remaining regressions from the rewrite now: https://github.com/react-native-community/react-native-svg/compare/SVGLength
Now it should be more spec conformant, stable, faster, memory efficient and easier to read.

**Comment by janicduplessis** [comment]
@msand I can post in the release repo to get it included in the next minor release if there is one.

Nice! Is that on npm? I'm planning a release of my app soon so I can test it.

**Comment by msand** [comment]
@janicduplessis Excellent! Now it is, v7.2.0 just published 🎉 https://www.npmjs.com/package/react-native-svg/v/7.2.0

**Comment by msageryd** [comment]
@msand Sorry for being late to the game. Every performance optimisation is great news to me. Unfortunately I ran into a wall here. I don't know where to start searching.

This is what I get when I mount the "drawing view" in my app using RNSVG 7.2
![image](https://user-images.githubusercontent.com/4483085/47210221-a911c480-d392-11e8-88aa-397a4dedcf33.png)

I have searched through my code in the hope to find any place where I have used strings instead of numbers. I only found one place, but changing this to numbers didn't fix the problem.

The reason I have one place where I'm using strings is that width and height of `<Use>` did not accept numbers previously. Should I use numbers in 7.2?

Here is my previous workaround in order to get `Use`to work:

```
      <Use
        href={this.getSymbolHref()}
        transform={transform}
        x={pos.x}
        y={pos.y}
        width={pos.symbolSize + ''}
        height={pos.symbolSize + ''}
      />
```

Do you have any clues of what to look for?

**Comment by msageryd** [comment]
I have dug into this. I managed to isolate the problem to a very simple line drawing.

This works:
``` 
return (
      <G>
        <Line x1={'10'} y1={'40'} x2={'40'} y2={'40'} stroke={'gray'} strokeWidth={8} />
      </G>
    );
```

This does not work:
``` 
return (
      <G>
        <Line x1={10} y1={40} x2={40} y2={40} stroke={'gray'} strokeWidth={8} />
      </G>
    );
```

The coordinates must be strings to work. The strokeWidth can be numerical, though.

I also got the below warning:
I have set `pointerEvents` to "none" on my Svg element. I don't set pointerEvents at G elements, though. This seems to be something RNSVG does internaly.

![image](https://user-images.githubusercontent.com/4483085/47211181-2a6a5680-d395-11e8-9ef2-5cf01317d33a.png)

This is how the properties of my Svg element is set:

```
<Svg
  width={data.viewPortRect.width()}
  height={data.viewPortRect.height()}
  pointerEvents={'none'}
>
```

**Comment by msand** [comment]
@msageryd Hmm, both those examples work fine for me in v7.2.0
I merged the PR from @janicduplessis to remove prop-types and released v8.0.0, so that warning won't be bothering you again ;)

**Comment by msand** [comment]
I've made the Svg element return a G element and set some of the styles and props from the root element on it, to allow inheritance of values without another significant refactor, should perhaps omit a bit more of the properties, but don't know of any actual issues that could result from it as of now. So, all Svg content currently have an implicit G element in the root.

**Comment by msand** [comment]
@msageryd Regarding numbers and strings, I recommend using numbers, but both should work, it's just that numbers are cheaper with regards to memory, cpu and energy. Much of the recent work has been to optimize for the case when the arguments are plain numbers rather than string encoded.

**Comment by msand** [comment]
@msageryd From the error message, it seems like these two lines would be missing from the code you've built: https://github.com/react-native-community/react-native-svg/blob/75204047c9424c591ed42d9763d6547709cf2b8b/ios/ViewManagers/RNSVGNodeManager.m#L176-L177
Can you try a clean rebuild with v8?
Otherwise, can you try adding those two lines somewhere together with these (e.g. before or after) : https://github.com/react-native-community/react-native-svg/blob/75204047c9424c591ed42d9763d6547709cf2b8b/ios/ViewManagers/RNSVGUseManager.m#L21-L32

**Comment by msand** [comment]
@msageryd perhaps you were using the plain-views branch? I tested in the master branch (essentially the SVGLength branch + some minor fixes, which builds on the plain-views one).

**Comment by janicduplessis** [comment]
Good news, the fix will make it in the next rn minor https://github.com/react-native-community/react-native-releases/issues/48#issuecomment-431416538

**Comment by msand** [comment]
Thanks for reporting, will look at it later tonight once I get back to a computer

**Comment by janicduplessis** [comment]
@msand Thanks!!

**Comment by msand** [comment]
@janicduplessis I think I've fixed the issue, really wouldn't expected this to be necessary changes to the code. But oh well, yet another day to learn about obj-c intricacies. https://github.com/react-native-community/react-native-svg/commit/e5768133295cbd4e70f4ab339d0aba1d1ad759b5

**Comment by janicduplessis** [comment]
@msand Awesome, thanks! I just tested master and everything works fine.

**Comment by JNUfeatherwit** [comment]
i have the same problem sometimes,but after reloading the react native app the crash will disappear .I don't know Why?

**Comment by iamdurui** [comment]
@janicduplessis  And my react native version is 0.56.0, if I upgrade the version from my current version to 0.57.4, I can solve this bug(ReadableNativeArray cannot be cast to java.lang.Double)
