### ISSUE TITLE
 Unable to resolve module `../lib/PATTERN_UNITS`

### ISSUE THREAD

**Issue by aleppos** [react-native-community/react-native-svg#814]
react-native-svg: 7.1.2

Looking for JS files in
   C:\Users\dev\**

Loading dependency graph, done.
::ffff:127.0.0.1 - - [15/Oct/2018:17:05:48 +0000] "GET /onchange HTTP/1.1" - - "-" "okhttp/3.11.0"
error: bundling failed: Error: Unable to resolve module `../lib/PATTERN_UNITS` from `C:\Users\dev\**\node_modules\react-native-svg\elements\Pattern.js`: The module `../lib/PATTERN_UNITS` could not be found from `C:\Users\dev\**\node_modules\react-native-svg\elements\Pattern.js`. Indeed, none of these files exist:
  * `C:\Users\dev\**\node_modules\react-native-svg\lib\PATTERN_UNITS(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `C:\Users\dev\**\node_modules\react-native-svg\lib\PATTERN_UNITS\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Users\dev\**\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:209:697)
    at ResolutionRequest.resolveDependency (C:\Users\dev\**\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (C:\Users\dev\**\node_modules\metro\src\node-haste\DependencyGraph.js:238:485)
    at Object.resolve (C:\Users\dev\**\node_modules\metro\src\lib\transformHelpers.js:180:25)
    at dependencies.map.result (C:\Users\dev\**\node_modules\metro\src\DeltaBundler\traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\dev\**\node_modules\metro\src\DeltaBundler\traverseDependencies.js:307:16)
    at C:\Users\dev\**\node_modules\metro\src\DeltaBundler\traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (C:\Users\dev\**\node_modules\metro\src\DeltaBundler\traverseDependencies.js:266:307)
 BUNDLE  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 60.5% (743/955), failed.

**Comment by msand** [comment]
Seems you have some caching issues. Try
```
watchman watch-del-all
rm -fr $TMPDIR/react-*
npm start -- --reset-cache
```
Or, 
```
rm -rf node_modules
npm i
npm start -- --reset-cache
```
v7.1.2 doesn't have the import your error refers to, it imports from "../lib/units" instead of "../lib/PATTERN_UNITS":
https://github.com/react-native-community/react-native-svg/blob/v7.1.2/elements/Pattern.js#L5
