### ISSUE TITLE
Android: SVG percentage height width crash on version > 6.5.2

### ISSUE THREAD

**Issue by netmaxt3r** [react-native-community/react-native-svg#823]
We are facing issue while upgraded our project from rnsvg from 6.5.2 on android. below is sample code on a bare react native project 
```xml
<View style={styles.container}>
	<Text style={styles.welcome}>Welcome to React Native!</Text>
	<Text style={styles.instructions}>To get started, edit App.js</Text>
	<Text style={styles.instructions}>{instructions}</Text>
	<View style={{height: 100, width: 100}}>
		<Svg width={"100%"} height={"100%"}>
			<Rect x="0" y="0" width="100" height="100" fill="black"/>
			<Circle cx="50" cy="50" r="30" fill="yellow"/>
			<Circle cx="40" cy="40" r="4" fill="black"/>
			<Circle cx="60" cy="40" r="4" fill="black"/>
			<Path d="M 40 60 A 10 10 0 0 0 60 60" stroke="black"/>
		</Svg>
	</View>
</View>
```
I tried version 8.0.5 master branch, plain-view branch and android app is crashing in all of them
logcat output 
```

10-24 14:50:44.706 29674 29674 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1032)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:999)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:949)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:910)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.horcrux.svg.SvgView.drawOutput(SvgView.java:216)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.horcrux.svg.SvgView.onDraw(SvgView.java:89)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20352)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19297)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20075)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:697)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20355)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19297)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20075)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19288)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20075)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19288)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20075)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19288)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20075)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.draw(View.java:20355)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:979)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:19297)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3488)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3275)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2810)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-24 14:50:44.706 29674 29674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Versions
React-native: 0.57.3
react-native-svg:8.0.5

works perfectly on version 6.5.2

related closed ticket [#3](https://github.com/react-native-community/react-native-svg/issues/3)

**Comment by msand** [comment]
@netmaxt3r Hmm, strange, can you make full replication? This seems to work fine for me:

```jsx
// @flow
import React from "react";
import { StyleSheet, View, Text } from "react-native";
import { Svg, Rect, Circle, Path } from "react-native-svg";

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Welcome to React Native!</Text>
        <View style={{ height: 100, width: 100 }}>
          <Svg width={"100%"} height={"100%"}>
            <Rect x="0" y="0" width="100" height="100" fill="black" />
            <Circle cx="50" cy="50" r="30" fill="yellow" />
            <Circle cx="40" cy="40" r="4" fill="black" />
            <Circle cx="60" cy="40" r="4" fill="black" />
            <Path d="M 40 60 A 10 10 0 0 0 60 60" stroke="black" />
          </Svg>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
});

```

**Comment by netmaxt3r** [comment]
holy molly, can u try add a backgroundColor to your container style and check its working for u? thats the only diff i have against i can see from ur code?

**Comment by netmaxt3r** [comment]
@msand 
please check this pull req
