### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by Iskander508** [react-native-community/react-native-svg#871]
Crash when trying to render an svg element. Happens on both debug/release. Multiple devices Android ranging from Android v6 to 8.

`    --------- beginning of crash
2018-12-11 10:56:42.722 13880-13880/com.XXXXXXXXXXXXX E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXXXXXXXX, PID: 13880
    java.lang.NullPointerException: Attempt to read from field 'com.horcrux.svg.SVGLength com.horcrux.svg.MaskView.mX' on a null object reference
        at com.horcrux.svg.RenderableView.render(RenderableView.java:268)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:99)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:309)
        at com.horcrux.svg.GroupView.drawGroup(GroupView.java:99)
        at com.horcrux.svg.GroupView.draw(GroupView.java:81)
        at com.horcrux.svg.RenderableView.render(RenderableView.java:309)
        at com.horcrux.svg.SvgView.drawChildren(SvgView.java:279)
        at com.horcrux.svg.SvgView.drawOutput(SvgView.java:232)
        at com.horcrux.svg.SvgView.onDraw(SvgView.java:89)
        at android.view.View.draw(View.java:19132)
        at android.view.View.updateDisplayListIfDirty(View.java:18082)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.draw(View.java:19135)
        at android.view.View.updateDisplayListIfDirty(View.java:18082)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.draw(View.java:19135)
        at android.view.View.updateDisplayListIfDirty(View.java:18082)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:699)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at android.view.View.updateDisplayListIfDirty(View.java:18073)
        at android.view.View.draw(View.java:18860)
2018-12-11 10:56:42.723 13880-13880/com.XXXXXXXX E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:4214)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4000)
        at android.view.View.draw(View.java:19135)
        at com.android.internal.policy.DecorView.draw(DecorView.java:794)
        at android.view.View.updateDisplayListIfDirty(View.java:18082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2994)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2798)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2351)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6754)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:713)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6589)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

libs used in the app:
`"dependencies": {
    "lodash": "4.17.11",
    "moment": "2.22.2",
    "prop-types": "15.6.2",
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-camera": "1.5.1",
    "react-native-clock-interval": "1.0.7",
    "react-native-config": "0.11.7",
    "react-native-device-info": "0.24.3",
    "react-native-firebase": "5.1.0",
    "react-native-gesture-handler": "1.0.10",
    "react-native-keyboard-aware-scroll-view": "0.7.4",
    "react-native-modal-translucent": "---custom---",
    "react-native-phone-call": "1.0.9",
    "react-native-popup-menu": "0.14.1",
    "react-native-qrcode-svg": "5.1.0",
    "react-native-screens": "1.0.0-alpha.17",
    "react-native-splash-screen": "---custom---",
    "react-native-svg": "8.0.9",
    "react-native-vector-icons": "6.1.0",
    "react-navigation": "3.0.5",
    "react-redux": "6.0.0",
    "redux": "4.0.1",
    "tinycolor2": "1.4.1",
    "weekstart": "1.0.0"
  }`

**Comment by Iskander508** [comment]
Found the culprit - mask property on G:
Example:
`const Example = ({ size }) => (
  <Svg width={size} height={size} viewBox="0 0 96 96">
    <Defs>
      <ClipPath id="mask-2" fill="white">
        <Circle cx="48" cy="48" r="48" />
      </ClipPath>
    </Defs>
    <G
      stroke="none"
      strokeWidth="1"
      fill="none"
      fillRule="evenodd"
      **mask="url(#mask-2)"**
    >
      <Circle cx="48" cy="48" r="48" fill="#FFD00B" fillRule="evenodd" />
    </G>
  </Svg>
);`

Using clipPath instead works.

**Comment by msand** [comment]
We should probably add some null checks after the lookup of mask, and only do the masking logic if the referenced element actually exists.

**Comment by tsdmrfth** [comment]
Same issue here and i did not understand the @Iskander508 's solution

**Comment by Iskander508** [comment]
It was a wrong definition in the svg itself. Wrong use of the mask prop. Can you share your svg which causes the crash? Maybe we can fix it.
