### ISSUE TITLE
[android crash] ViewManager: Error while updating prop x

### ISSUE THREAD

**Issue by JNUfeatherwit** [react-native-community/react-native-svg#873]
This bug sometimes occurs, but sometimes it doesn't.Upgrading to the latest version has no effect.I have been troubled by this problem for a long time.
### version
"react-native": "0.55.4"
"react-native-svg": "^8.0.10"
"react": "16.3.1"
```
2018-12-12 11:13:59.318 31835-31835/cn.ut.orion E/unknown:ViewManager: Error while updating prop x
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at android.support.v4.util.Pools$SimplePool.acquire(Pools.java:106)
        at com.facebook.react.bridge.DynamicFromMap.create(DynamicFromMap.java:27)
        at com.facebook.react.bridge.ReadableNativeMap.getDynamic(ReadableNativeMap.java:207)
        at com.facebook.react.uimanager.ReactStylesDiffMap.getDynamic(ReactStylesDiffMap.java:86)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$DynamicPropSetter.extractProperty(ViewManagersPropertyCache.java:132)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:79)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1012)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:983)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:718)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7383)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
2018-12-12 11:13:59.320 31835-31835/cn.ut.orion E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'x' of a view managed by: RNSVGRect
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:92)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1012)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:983)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:718)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7383)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at android.support.v4.util.Pools$SimplePool.acquire(Pools.java:106)
        at com.facebook.react.bridge.DynamicFromMap.create(DynamicFromMap.java:27)
        at com.facebook.react.bridge.ReadableNativeMap.getDynamic(ReadableNativeMap.java:207)
        at com.facebook.react.uimanager.ReactStylesDiffMap.getDynamic(ReactStylesDiffMap.java:86)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$DynamicPropSetter.extractProperty(ViewManagersPropertyCache.java:132)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:79)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:232) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1012) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:983) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:790) 
        at android.view.Choreographer.doFrame(Choreographer.java:718) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967) 
        at android.os.Handler.handleCallback(Handler.java:809) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7383) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
```

**Comment by JNUfeatherwit** [comment]
sometimes the error is 'error while updating prop height' or 'error while updating prop width' or  'error while updating prop marginRight'

**Comment by JNUfeatherwit** [comment]
> Try upgrading to react-native 0.57.4 or newer [#806 (comment)](https://github.com/react-native-community/react-native-svg/issues/806#issuecomment-431452253)

Thank you for answering。But for us,  it is unlikely to upgrading rn.So I rolled back the version of react-native-svg to 6.0.0.Is it ok?

**Comment by msand** [comment]
Well, that's just up to you. Alternatively you can apply the patch to the version of rn you are using and build it yourself (requires ndk)

**Comment by devmark88** [comment]
@msand is this exception catchable in componentDidCatch method of the application component (not your component)?

**Comment by msand** [comment]
Closing, as it's a bug in react-native, and fixed in the latest versions.

**Comment by edo1493** [comment]
I have the same in 9.4.0 by using react-native-svg-charts.

This has started to happen after I bumbed it to 9.4.0 from 6.0.0+.

It's weird cause it happens on a handful of devices and if we ask people to uninstall/reinstall, it will work just fine.
