### ISSUE TITLE
Crash on android when using Mask

### ISSUE THREAD

**Issue by SimenB** [react-native-community/react-native-svg#980]
Snack: https://snack.expo.io/@folio/expo.svg-example

Removing the mask in the middle makes it not crash.

This same SVG renders correctly on both web and iOS, it's just Android that crashes.

Svg:

```tsx
<Svg
  width={22}
  height={22}
  viewBox="0 0 22 22"
  fill="none"
  color="black"
>
  <Svg.Path
    d="M19.142 8.515a1 1 0 0 0 0-1.414l-1.414-1.415a1 1 0 0 0-1.414 0l-8.337 8.337a4 4 0 0 0-1.089 2.037l-.474 2.354 2.355-.474a4 4 0 0 0 2.036-1.088l8.337-8.337z"
    stroke="currentColor"
    strokeWidth={2}
    strokeLinecap="round"
  />
  <Svg.Mask id="prefix__a" fill="#fff">
    <Svg.Path d="M17.5 10.5l-3-3L17 5l3 3-2.5 2.5z" />
  </Svg.Mask>
  <Svg.Path
    d="M14.5 7.5l-1.414-1.414a2 2 0 0 0 0 2.828L14.5 7.5zm3 3l-1.414 1.414a2 2 0 0 0 2.828 0L17.5 10.5zM20 8l1.414 1.414a2 2 0 0 0 0-2.828L20 8zm-3-3l1.414-1.414a2 2 0 0 0-2.828 0L17 5zm-3.914 3.914l3 3 2.828-2.828-3-3-2.828 2.828zm5.828 3l2.5-2.5-2.828-2.828-2.5 2.5 2.828 2.828zm2.5-5.328l-3-3-2.828 2.828 3 3 2.828-2.828zm-5.828-3l-2.5 2.5 2.828 2.828 2.5-2.5-2.828-2.828z"
    fill="currentColor"
    mask="url(#prefix__a)"
  />
  <Svg.Path
    d="M10 5a1 1 0 1 0 0-2v2zM3 3a1 1 0 0 0 0 2V3zm7 0H3v2h7V3zM6 9a1 1 0 0 0 0-2v2zM3 7a1 1 0 0 0 0 2V7zm3 0H3v2h3V7z"
    fill="currentColor"
  />
</Svg>
```

Stack traces:

<details>

```
03-22 16:15:11.550  9876  9876 E AndroidRuntime: FATAL EXCEPTION: main
03-22 16:15:11.550  9876  9876 E AndroidRuntime: Process: host.exp.exponent, PID: 9876
03-22 16:15:11.550  9876  9876 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'abi32_0_0.host.exp.exponent.modules.api.components.svg.SVGLengthUnitType abi32_0_0.host.exp.exponent.modules.api.components.svg.SVGLength.unit' on a null object reference
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.VirtualView.relativeOnWidth(VirtualView.java:331)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:270)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.GroupView.drawGroup(GroupView.java:99)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.GroupView.draw(GroupView.java:81)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.RenderableView.render(RenderableView.java:311)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawChildren(SvgView.java:279)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.SvgView.drawOutput(SvgView.java:232)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.host.exp.exponent.modules.api.components.svg.SvgView.onDraw(SvgView.java:89)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:20207)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19082)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:702)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19073)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:702)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:20210)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19082)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:702)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19073)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:20210)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.widget.ScrollView.draw(ScrollView.java:1739)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:377)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19082)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:20210)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19082)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.draw(View.java:19935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at abi32_0_0.com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:702)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19073)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.View.updateDisplayListIfDirty(View.java:19042)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.Choreographer.doFrame(Choreographer.java:696)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:873)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:193)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6718)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-22 16:15:11.550  9876  9876 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Comment by msand** [comment]
I'm unable to replicate in the latest version. Can you eject from Expo / use plain react-native?

**Comment by msand** [comment]
If you can't upgrade, then you can specify x y width and height attributes on the Mask element to workaround the bug in the old version: https://snack.expo.io/@msand/forlorn-almond

```jsx
import React, { Component } from 'react';
import { View } from 'react-native';
import { Constants, Svg } from 'expo';
const { Path, Mask } = Svg;

export default class App extends Component {
  state = { a: false };
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Svg
          width="22"
          height="22"
          viewBox="0 0 22 22"
          fill="none"
          color="black">
          <Path
            d="M19.142 8.515a1 1 0 0 0 0-1.414l-1.414-1.415a1 1 0 0 0-1.414 0l-8.337 8.337a4 4 0 0 0-1.089 2.037l-.474 2.354 2.355-.474a4 4 0 0 0 2.036-1.088l8.337-8.337z"
            stroke="currentColor"
            strokeWidth={2}
            strokeLinecap="round"
          />
          <Mask id="prefix__a" fill="#fff" x="0" y="0" width="22" height="22">
            <Path d="M17.5 10.5l-3-3L17 5l3 3-2.5 2.5z" />
          </Mask>
          <Path
            d="M14.5 7.5l-1.414-1.414a2 2 0 0 0 0 2.828L14.5 7.5zm3 3l-1.414 1.414a2 2 0 0 0 2.828 0L17.5 10.5zM20 8l1.414 1.414a2 2 0 0 0 0-2.828L20 8zm-3-3l1.414-1.414a2 2 0 0 0-2.828 0L17 5zm-3.914 3.914l3 3 2.828-2.828-3-3-2.828 2.828zm5.828 3l2.5-2.5-2.828-2.828-2.5 2.5 2.828 2.828zm2.5-5.328l-3-3-2.828 2.828 3 3 2.828-2.828zm-5.828-3l-2.5 2.5 2.828 2.828 2.5-2.5-2.828-2.828z"
            fill="currentColor"
            mask="url(#prefix__a)"
          />
          <Path
            d="M10 5a1 1 0 1 0 0-2v2zM3 3a1 1 0 0 0 0 2V3zm7 0H3v2h7V3zM6 9a1 1 0 0 0 0-2v2zM3 7a1 1 0 0 0 0 2V7zm3 0H3v2h3V7z"
            fill="currentColor"
          />
        </Svg>
      </View>
    );
  }
}

```

**Comment by SimenB** [comment]
Thanks! That makes it not crash, but it doesn't render correctly. It's rendering the same as if the mask and the path after it is not there at all.

Correct: 
![image](https://user-images.githubusercontent.com/1404810/54910707-2666d580-4eed-11e9-9a5d-740e2a520aac.png)

Without mask:
![image](https://user-images.githubusercontent.com/1404810/54910716-2bc42000-4eed-11e9-9995-9f759ad8f4e9.png)

However, if this is fixed in a newer release, we're fine to wait until that's released in Expo 🙂 If you can confirm it's rendered correctly on the latest release, feel free to close this issue (we'll probably just rework the svg itself to not use a mask)

**Comment by msand** [comment]
Yeah, it seems to work correctly in the latest version. But in cases like these (I assume this svg was made with sketch) where the mask is really not useful nor necessary, its computationally very very expensive to use a mask to fill in a square shape area with a single color without dependence on the alpha transparency of the source graphic for the mask. It's just plain redundant, slow and a memory hog, for no additional benefit. I would rewrite this code by hand (and essentially anything coming from the extremely inefficient sketch svg generator and similar tools) to something like this:
```jsx
import React, { Fragment, Component, PureComponent } from 'react';
import { View, StyleSheet } from 'react-native';
import Svg, { Path } from 'react-native-svg';

const icon = (
  <Fragment>
    <Path d="M17.5 10.5l-3-3L17 5l3 3-2.5 2.5z" fill="currentColor" />
    <Path
      d="M19.142 8.515a1 1 0 0 0 0-1.414l-1.414-1.415a1 1 0 0 0-1.414 0l-8.337 8.337a4 4 0 0 0-1.089 2.037l-.474 2.354 2.355-.474a4 4 0 0 0 2.036-1.088l8.337-8.337z"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
    />
    <Path
      d="M10 5a1 1 0 1 0 0-2v2zM3 3a1 1 0 0 0 0 2V3zm7 0H3v2h7V3zM6 9a1 1 0 0 0 0-2v2zM3 7a1 1 0 0 0 0 2V7zm3 0H3v2h3V7z"
      fill="currentColor"
    />
  </Fragment>
);

class SvgComponent extends PureComponent {
  render() {
    return (
      <Svg
        width="122"
        height="122"
        viewBox="0 0 22 22"
        fill="none"
        color="black"
        {...this.props}
      >
        {icon}
      </Svg>
    );
  }
}

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <SvgComponent />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'lightgray',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
});

```

**Comment by SimenB** [comment]
The illustration was made in Figma and exported as svg, not sketch. Probably a very similar thing, though! But yeah, I totally agree it should be simplified. Thank you for looking into it!

**Comment by SimenB** [comment]
We've got a way simpler version now, thanks for the feedback!
